---
title: "GroupingNestingMapping"
output: html_notebook
---

```{r libraries}
library("tidyverse")
library("modelr")
library("broom")
```

```{r tibble df}
df <- tibble(x = c(1:6), y = rep(c("a","b"), times = 3), z = seq(10,20, by = 2))
df
```

```{r apply function to df}
df %>%
  mutate(a = mean(z))
```

```{r group}
df_group = df %>%
  group_by(y)

df_group
```


```{r apply function to df_group}
df_group %>%
  mutate(a = mean(z))
```

```{r nest df_group}
df_nest <- df_group %>%
  nest()

df_nest
```

```{r inspect nest}
df_nest$data[[1]]
```

```{r map df_nest}
df_nest <- df_nest %>%
  mutate(NestAv = map_dbl(data, ~mean(.$z)))

df_nest
```


```{r map model}
df_nest <- df_nest %>%
  mutate(LinModel = map(data, ~lm(z ~ x, data = .)))

df_nest 
```
Inspect Model
```{r inspect model}
df_nest$LinModel[[1]]
```

Mpdel outputs from R are in 'list' format, and are not consistent across model functions.

'tidy::broom' can help.

```{r model output}
df_nest <- df_nest %>%
  mutate(ModelCoeff = map(LinModel, tidy))

df_nest

df_nest$ModelCoeff[[1]]
```
Extracting Individual Coefficients
```{r unnesting}
df_unnest <- df_nest %>% 
  unnest(ModelCoeff)

df_unnest
```

Pivot wider
```{r}
df_wide <- df_unnest %>%
  pivot_wider(data = ., names_from = term, values_from = c(estimate, std.error, statistic, p.value ))

df_wide
```



What if model fails on some data subsets?
```{r possibly}
df2 <- tibble(x = c(1, 2, NA, 4,5,NA, 7, 8, NA), y = rep(c("a","b","c"), times = 3), z = c(10, 12, NA, 16, 18, NA, 22, 24, NA))

df2

df2_nest <- df2 %>%
  group_by(y) %>%
  nest() %>%
  mutate(LinModel = map(data, ~lm(z ~ x, data = .)))

#possibly (alternative to 'trycatch')
df2_nest <- df2 %>%
  group_by(y) %>%
  nest() %>%
  mutate(LinModel = map(data, possibly(~lm(z ~ x, data = .), otherwise = NULL)))

df2_nest
```