---
title: "Live Code GroupingNestingMapping"
output: html_notebook
---

Content drawn largely from R for Data Science online book; ch. 21.5 & 25
https://r4ds.had.co.nz/

```{r libraries}
library("tidyverse")
library("modelr")
library("broom")
```

```{r tibble df}
df <- tibble(x = c(1:6), y = rep(c("a", "b"), times = 3), z = seq(10, 20, by = 2))
df
```

```{r apply function to df}
df %>%
  mutate(a = mean(z))
```

```{r group}
df_group <- df %>%
  group_by(y)

df_group
```
```{r apply function to df_group}
df_group %>%
  mutate(a = mean(z))
```

```{r nest df_group}
df_nest <- df_group %>%
  nest()

df_nest

df_nest$data[[1]]
```
```{r nest direct}
df_nest_direct <- df %>%
  nest(data = c(x, z))

df_nest_direct

df_nest_direct$data[[1]]
```
```{r map df_nest}
df_nest2 <- df_nest %>%
  mutate(NestXAv = map_dbl(data, ~mean(.$x)),
         NestZAv = map_dbl(data, ~mean(.$z)))

df_nest2

```


```{r map model}
df_nest3 <- df_nest %>%
  mutate(LinModel = map(data, ~lm(z ~ x, data = .)))

df_nest3 
```
Model outputs from R are in 'list' format (list objects), and are not consistent across model functions.

```{r inspect model}
df_nest3$LinModel[[1]]
```

broom::tidy can help generate more accessible outputs from most model functions available in R
```{r model output}
df_nest3 <- df_nest3 %>%
  mutate(ModelCoeff = map(LinModel, tidy))

df_nest3

df_nest3$ModelCoeff[[1]]
```
Extract Individual Coefficients
```{r unnesting}
df_unnest <- df_nest3 %>%
  unnest(ModelCoeff)

df_unnest
```

pivot_wider
```{r pivot terms to their own columns}
df_wide <- df_unnest %>%
  pivot_wider(data = ., names_from = term, values_from = c(estimate, std.error, statistic, p.value))

df_wide
```

What if the model fails on some data subsets?
```{r possibly}
df2 <- tibble(x = c(1, 2, NA, 4, 5, NA, 7, 8, NA), y = rep(c("a", "b", "c"), times = 3), z = c(10, 12, NA, 16, 18, NA, 22, 24, NA))

df2

df2_nest <- df2 %>%
  group_by(y) %>%
  nest() %>%
  mutate(LinModel = map(data, ~lm(z ~ x, data = .)))

#possibly (tidyverse alternative to 'trycatch')

df2_nest <- df2 %>%
  group_by(y) %>%
  nest() %>%
  mutate(LinModel = map(data, possibly(~lm(z ~ x, data = .), otherwise = NULL)))

df2_nest

df2_nest$LinModel[[3]]
```

```{r test nest}
test_nest <- df %>%
  nest()

test_nest

test_nest$data

test_nest2 <- df %>%
  nest(-c(y))

test_nest2

df <- df %>%
  mutate(b = c("m","m", "m", "n","n","n"))

df

test_nest3 <- df %>%
  nest(-c(y, b))

test_nest3

test_nest3$data[[1]]

test_nest4 <- df %>%
  group_by(y, b) %>%
  nest()

test_nest4
```

